// lib/client-strings.ts - The UI strings each interactive (client)
// component needs, picked on the server and passed down as a `strings` prop.
//
// Client components must never import lib/translations.ts: that ships the
// whole dictionary to the browser.
// Client components import only the ClientStrings *type* from here.
//
// Adding a translate('new_key') call to a client component? Add the key to
// its list below - TypeScript fails the build until you do.

import { translate } from './translations';

export const CLIENT_KEYS = {
  deadPixelTest: [
    'dead_pixel_aspect_ratio_label',
    'dead_pixel_auto_cycle_label',
    'dead_pixel_click_fullscreen_hint',
    'dead_pixel_current_color_label',
    'dead_pixel_desktop_test_button',
    'dead_pixel_exit_button',
    'dead_pixel_how_to_test_label',
    'dead_pixel_how_to_test_text',
    'dead_pixel_keyboard_hint',
    'dead_pixel_mobile_test_button',
    'dead_pixel_next_button',
    'dead_pixel_next_color_button',
    'dead_pixel_previous_button',
    'dead_pixel_previous_color_button',
    'dead_pixel_rgb_label',
    'dead_pixel_select_color_prefix',
    'dead_pixel_start_button',
    'dead_pixel_start_fullscreen_aria',
    'dead_pixel_start_test_button',
    'dead_pixel_stop_button',
    'dead_pixel_test_colors_label',
  ],
  screenDisplay: [
    'color_customizer_darker',
    'color_customizer_hex_label',
    'color_customizer_lighter',
    'color_customizer_picker_label',
    'color_customizer_reset_button',
    'color_customizer_rgb_label',
    'color_customizer_toggle',
    'color_customizer_tone_label',
    'keyboard_shortcuts',
    'screen_display_click_to_fullscreen',
    'screen_display_copied_hint',
    'screen_display_custom_color',
    'screen_display_download_btn',
    'screen_display_exit_fullscreen_hint',
    'screen_display_fullscreen_aria',
    'screen_display_fullscreen_btn',
    'screen_display_height_label',
    'screen_display_keyboard_hint',
    'screen_display_pick_color',
    'screen_display_presets',
    'screen_display_title',
    'screen_display_width_label',
  ],
  colorCustomizer: [
    'color_customizer_darker',
    'color_customizer_hex_label',
    'color_customizer_lighter',
    'color_customizer_picker_label',
    'color_customizer_reset_button',
    'color_customizer_rgb_label',
    'color_customizer_toggle',
    'color_customizer_tone_label',
  ],
  brightnessTest: [
    'brightness_auto_cycle_button',
    'brightness_black_label',
    'brightness_desktop_button',
    'brightness_display_opacity_hint',
    'brightness_display_opacity_label',
    'brightness_flicker_frequency_hint',
    'brightness_flicker_frequency_label',
    'brightness_flicker_test_hint',
    'brightness_flicker_test_title',
    'brightness_fullscreen_button',
    'brightness_gradient_test_hint',
    'brightness_gradient_test_subtitle',
    'brightness_gradient_test_title',
    'brightness_gray_navigation_label',
    'brightness_mobile_button',
    'brightness_mode_bars',
    'brightness_mode_flicker',
    'brightness_mode_gradient',
    'brightness_mode_ladder',
    'brightness_navigate_label',
    'brightness_pause_button',
    'brightness_reset_button',
    'brightness_white_label',
    'keyboard_shortcuts',
  ],
  contrastTest: [
    'contrast_background_label',
    'contrast_color_transformation_label',
    'contrast_copy_button',
    'contrast_custom_pair_text',
    'contrast_custom_pair_title',
    'contrast_foreground_label',
    'contrast_fullscreen_button',
    'contrast_mode_custom_pair',
    'contrast_mode_patterns',
    'contrast_mode_readability',
    'contrast_mode_wcag_ladder',
    'contrast_pair_label',
    'contrast_pattern_hint',
    'contrast_pattern_title',
    'contrast_ratio_label',
    'contrast_readability_small_text_hint',
    'contrast_readability_test_title',
    'contrast_readability_text',
    'contrast_reset_button',
    'contrast_shortcuts_label',
    'contrast_test_title',
    'contrast_vision_hint',
    'contrast_vision_simulation_label',
  ],
  backlightBleedDisplay: [
    'keyboard_shortcuts',
    'screen_display_exit_fullscreen_hint',
    'screen_display_fullscreen_btn',
  ],
  motionTestDisplay: [
    'keyboard_shortcuts',
    'screen_display_exit_fullscreen_hint',
    'screen_display_fullscreen_btn',
  ],
  pixelDensityCalculator: [
    'pixel_density_category_high',
    'pixel_density_category_low',
    'pixel_density_category_standard',
    'pixel_density_category_ultra',
    'pixel_density_category_very_high',
    'pixel_density_display_quality_label',
    'pixel_density_dpi_label',
    'pixel_density_horizontal_resolution_label',
    'pixel_density_placeholder_horizontal',
    'pixel_density_placeholder_size',
    'pixel_density_placeholder_vertical',
    'pixel_density_ppi_label',
    'pixel_density_professional_use_label',
    'pixel_density_quality_high',
    'pixel_density_quality_indicators_label',
    'pixel_density_quality_low',
    'pixel_density_quality_standard',
    'pixel_density_quality_ultra',
    'pixel_density_quality_very_high',
    'pixel_density_quick_presets',
    'pixel_density_reference_guide_title',
    'pixel_density_reference_high',
    'pixel_density_reference_low',
    'pixel_density_reference_standard',
    'pixel_density_reference_ultra',
    'pixel_density_screen_size_label',
    'pixel_density_sharpness_label',
    'pixel_density_text_clarity_label',
    'pixel_density_vertical_resolution_label',
  ],
  deadPixelFixer: [
    'btn_fullscreen',
    'btn_reset',
    'btn_start_repair',
    'btn_stop',
    'can_stuck_pixels_be_fixed_p1',
    'can_stuck_pixels_be_fixed_p2',
    'can_stuck_pixels_be_fixed_p3',
    'can_stuck_pixels_be_fixed_title',
    'dead_pixel_faq_title',
    'dead_pixel_fixer',
    'dead_pixel_fixer_how_to_intro',
    'dead_pixel_fixer_how_to_title',
    'dead_pixel_fixer_intro',
    'dead_pixel_fixer_main_title',
    'dead_pixel_fixer_pro_tip',
    'dead_pixel_fixer_step1',
    'dead_pixel_fixer_step2',
    'dead_pixel_fixer_step3',
    'dead_pixel_fixer_step4',
    'dead_pixel_fixer_step5',
    'dead_pixel_fixer_step6',
    'dead_pixel_fixer_why_works_desc',
    'dead_pixel_fixer_why_works_title',
    'explore_guides_brightness',
    'explore_guides_brightness_desc',
    'explore_guides_color_screen',
    'explore_guides_color_screen_desc',
    'explore_guides_contrast',
    'explore_guides_contrast_desc',
    'explore_guides_dead_pixel_test',
    'explore_guides_dead_pixel_test_desc',
    'explore_guides_desc',
    'explore_guides_title',
    'flash_mode',
    'flash_speed',
    'flash_speed_fast',
    'flash_speed_slow',
    'hint_esc',
    'hint_f',
    'home',
    'lcd_displays_p1',
    'lcd_displays_p2',
    'lcd_displays_title',
    'lcd_vs_oled_intro',
    'lcd_vs_oled_title',
    'oled_displays_p1',
    'oled_displays_p2',
    'oled_displays_title',
    'resources',
    'stats_elapsed',
    'stats_fps',
    'stats_mode',
    'what_is_dead_pixel_p1',
    'what_is_dead_pixel_p2',
    'what_is_dead_pixel_p3',
    'what_is_dead_pixel_title',
    'what_is_stuck_pixel_p1',
    'what_is_stuck_pixel_p2',
    'what_is_stuck_pixel_p3',
    'what_is_stuck_pixel_title',
  ],
} as const;

export type ClientComponent = keyof typeof CLIENT_KEYS;
export type ClientStrings<C extends ClientComponent> = Record<(typeof CLIENT_KEYS)[C][number], string>;

export function getClientStrings<C extends ClientComponent>(component: C): ClientStrings<C> {
  return Object.fromEntries(
    CLIENT_KEYS[component].map((key: string) => [key, translate(key as never)])
  ) as ClientStrings<C>;
}
